[workspace]
resolver = "2"
members = [
    "rust/specter-wasm",
    "vendor/specter-core",
    "vendor/specter-crypto",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release.package."*"]
opt-level = "z"

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1
